### ISSUE TITLE
Leetcode problem : Flatten a binary tree to Linked list 

### ISSUE THREAD

**Issue by Jyoti040** [MdHRShohel/JS-OPP-DSA-Problems-Hacktoberfest2023#176]
I want to add solution of the leetcode problem of converting a binary tree to linked list

**Comment by thechangamunda** [comment]
I would like to work on this and could you add the label of hacktoberfest2023, it would be much appreciated.

**Comment by divya1515** [comment]
Please assign me this issue

**Comment by syedmaazsaeed** [comment]
you can assign me this Issue . I can eaisly solve this issue .

**Comment by syedmaazsaeed** [comment]
Hello. I hope you are well. Thanks for Merging my Pull request .
